SAVE_PILLAR='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/iconImage"])[7]'
CLASSIC_OPEN_ACCOUNT_BUTTON='xpath=(//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/actionOneButton"])[2]'
CLASSIC_SAVINGS_AMOUNT_FIELD='//android.widget.EditText[@resource-id="ke.co.equitygroup.equitymobile.debug:id/editTextValue"]'
CLASSIC_CONTINUE_ACTION_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/continueAction"]'
CLASSIC_TERMS_LINK='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/termsLink"]'
CLASSIC_TERMS_CHECKBOX='//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/iAcceptRadioButton"]'
CLASSIC_EXIT_TERMS='//android.widget.ImageButton[@content-desc="Navigate Up"]'
CLASSIC_APPLICATION_FEEDBACK='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/confirmationTitle"]'
CLASSIC_SUCCESS_TEXT='Congrats, you’re growing your wealth!'
CLASSIC_DONE_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/doneAction"]'
CLASSIC_CONFIRM_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/reviewContinueButton"]'
OPEN_SAVINGS_ACCOUNT_NAV='//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/linkAccountViewConstraint"]'
