SAVE_PILLAR='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/iconImage"])[7]'
CLASSIC_OPEN_ACCOUNT_BUTTON='xpath=(//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/actionOneButton"])[2]'
CLASSIC_SAVINGS_AMOUNT_FIELD='//android.widget.EditText[@resource-id="ke.co.equitygroup.equitymobile.debug:id/editTextValue"]'
CLASSIC_CONTINUE_ACTION_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/continueAction"]'
CLASSIC_TERMS_LINK='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/termsLink"]'
CLASSIC_TERMS_CHECKBOX='//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/iAcceptRadioButton"]'
CLASSIC_EXIT_TERMS='//android.widget.ImageButton[@content-desc="Navigate Up"]'
CLASSIC_APPLICATION_FEEDBACK='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/confirmationTitle"]'
CLASSIC_SUCCESS_TEXT='Congrats, you’re growing your wealth!'
CLASSIC_DONE_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/doneAction"]'
CLASSIC_CONFIRM_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/reviewContinueButton"]'
OPEN_SAVINGS_ACCOUNT_NAV='//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/linkAccountViewConstraint"]'

RECURRING_TRANSFER_BUTTON='//android.widget.Switch[@resource-id="ke.co.equitygroup.equitymobile.debug:id/reinvestmentSwitchAction"]'
SELECT_FREQUENCY_DROPDOWN='//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemDropDown"]'
DAILY_PAYMENT='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemText" and @text="Daily Payment"]'
WEEKLY_PAYMENT='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemText" and @text="Weekly Payment"]'
AMOUNT_FIELD='//android.widget.EditText[@resource-id="ke.co.equitygroup.equitymobile.debug:id/editTextValue"]'
FIRST_PAYMENT_CALENDER='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemCalendar"])[1]'
SELECTED_DATE_PEN='//android.widget.ImageButton[@content-desc="Switch to text input mode"]'
OK_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/confirm_button"]'
LAST_PAYMENT_CALENDER='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemCalendar"])[2]'
NEXT_MONTH_ARROW='//android.widget.Button[@content-desc="Change to next month"]'
CONTINUE_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/continueButton"]'

#CLASSIC_FIRST_CARD='xpath=(//android.widget.ImageView[@content-desc="Save"])[1]//(//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/accountName" and @text="Classic savings"])[1]'
#CLASSIC_FIRST_SAVE_CARD='xpath=(//android.widget.ImageView[@content-desc="Save"])[1]//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/accountName" and @text="Classic savings"]'
CLASSIC_FIRST_SAVE_CARD='xpath=(//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/accountName" and @text="Classic savings"])[3]'
#CLASSIC_SECOND_SAVE_CARD='xpath=(//android.widget.ImageView[@content-desc="Save"])[2]//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/accountName" and contains(@text, "Classic savings")]'
#CLASSIC_SECOND_SAVE_CARD='xpath=(//android.widget.ImageView[@content-desc="Save"])[2]/android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/accountName" and contains(@text, "Classic savings")]'
CLASSIC_SECOND_SAVE_CARD='xpath=(//android.widget.ImageView[@content-desc="Save"])[2]/following-sibling::android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/accountName" and contains(@text, "Classic savings")]'

CLASSIC_THIRD_SAVE_CARD='xpath=(//android.widget.ImageView[@content-desc="Save"])[3]//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/accountName" and @text="Classic savings"]'