FIXED_OPEN_ACCOUNT_BUTTON='xpath=(//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/actionOneButton"])[3]'
NO_SAVINGS_REFRESH_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/primaryButton"]'
NO_SAVINGS_DISMISS_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/secondaryButton"]'
NO_SAVINGS_DISPLAY='//android.view.View[@resource-id="ke.co.equitygroup.equitymobile.debug:id/statusContentView"]'
FIXED_AMOUNT_FIELD='//android.widget.EditText[@resource-id="ke.co.equitygroup.equitymobile.debug:id/editTextValue"]'
DEPOSIT_PERIOD_DROPDOWN='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemDropDown"])[2]'
#PERIOD_ELEMENT='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemText" and @text="3 Months"]'
#PERIOD_ELEMENT='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemText" and @text="${period}"]'
DEPOSIT_PERIOD_EXIT='//android.widget.ImageButton'
FIXED_CONTINUE_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/continueAction"]'
FIXED_DEPOSIT_CONFIRMATION='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/toolbarTitle"]'
FIXED_TERMS_LINK='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/termsLink"]'
FIXED_TERMS_PAGE='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/toolbarTitle" and @text="Terms"]'
FIXED_TERMS_EXIT='//android.widget.ImageButton[@content-desc="Navigate Up"]'
FIXED_TERMS_CHECKBOX='//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/iAcceptRadioButton"]'
FIXED_CONFIRM_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/reviewContinueButton"]'
FIXED_SUCCESS_FEEDBACK='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/confirmationTitle"]'
FIXED_SUCCESS_TEXT='Congrats, you’re growing your wealth!'
FIXED_DONE_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/doneAction"]'
CREATED_FIXED_CARD='//android.widget.ImageView[@content-desc="Save"]'

REINVEST_BUTTON='//android.widget.Switch[@resource-id="ke.co.equitygroup.equitymobile.debug:id/reinvestmentSwitchAction"]'
CHOOSE_REINVESTMENT_OPTION='//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/reinvestOptionValue"]'
REINVEST_PRINCIPAL_AND_INTEREST='xpath=(//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemRadioButton"])[3]'

FIXED_DEPOSIT_INFORMATION='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/title" and @text="Fixed deposit"]'
FIXED_DEPOSIT_VIEW_ALL='xpath=(//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/learnMoreAction"])[2]'
FIRST_FIXED_DEPOSIT_CARD='xpath=(//android.widget.ImageView[@content-desc="Save"])[3]'
SECOND_FIXED_DEPOSIT='xpath=(//android.widget.ImageView[@content-desc="Save"])[4]'
TRANSACTION_HISTORY='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/transaction_history_title"]'
FIXED_TRANSACTION_AMOUNT='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/transactionAmount"]'
FIXED_ACCOUNT_INFORMATION='//androidx.recyclerview.widget.RecyclerView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/accountActions"]/android.view.ViewGroup[1]'
FIXED_DEPOSIT_PERIOD='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/description" and @text="6 Months"]'
FIXED_INTEREST_RATE='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/description" and @text="3.5%"]'
INTEREST_RATE_INFORMATION='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/viewInterestRateLink"]'
FIXED_DEPOSIT_RATES='//android.widget.TextView[@text="Interest rates for Fixed Deposit in UGX"]'
LEAVE_INTEREST_RATE_PAGE='//android.widget.ImageButton'





