ALLOW_DEVICE_ACCESS_ONLY_TIME = "com.android.permissioncontroller:id/permission_allow_one_time_button"
ALLOW_DEVICE_ACCESS_WHILE_USING_THE_APP = "com.android.permissioncontroller:id/permission_allow_foreground_only_button"
DENY_PERMISSION = "com.android.permissioncontroller:id/permission_deny_button"
CHOOSE_LANGUAGE = "ke.co.equitygroup.equitymobile.debug:id/en"
CONTINUE_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/continueButton"
# Welcome to Equity mobile
ANCHOR_TOOLBAR_TITLE = "ke.co.equitygroup.equitymobile.debug:id/toolbarTitle"
SLIDER_TITLE = "ke.co.equitygroup.equitymobile.debug:id/sliderTitle"
#NEXT_BUTTON = "//android.widget.Button[@text='Next']"
NEXT_BUTTON = '//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/getStartedButton"]'
GET_STARTED_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/getStartedButton"
# Good afternoon! Sign in or register to continue
ANCHOR_SIGN_REGISTER_SCREEN = "ke.co.equitygroup.equitymobile.debug:id/welcomeSubText"
CHANGE_LANGUAGE = "ke.co.equitygroup.equitymobile.debug:id/changeLanguageLogo"
REGISTER_IN_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/signUpAction"
SIGN_IN_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/loginAction"
EMAIL_MOBILE_NUMBER_FIELD = '//android.widget.EditText[@text="Email address or mobile number"]'
PASSWORD_FIELD = '//android.widget.EditText[@text="Enter password"]'
LOGIN_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/loginButton"
SMS_RADIO_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/itemRadioButton"
#SMS_VERIFICATION_FIELD = "//android.widget.TextView[@resource-id='ke.co.equitygroup.equitymobile.debug:id/itemSubText' and @text='2*****']"
SMS_VERIFICATION_FIELD = "ke.co.equitygroup.equitymobile.debug:id/itemRadioButton"
EMAIL_VERIFICATION_FIELD = "//android.widget.TextView[@text= 'By Email']"
CONFIRM_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/confirmButton"
VERIFICATION_CODE_1 = "ke.co.equitygroup.equitymobile.debug:id/digit1"
VERIFICATION_CODE_2 = "ke.co.equitygroup.equitymobile.debug:id/digit2"
VERIFICATION_CODE_3 = "ke.co.equitygroup.equitymobile.debug:id/digit3"
VERIFICATION_CODE_4 = "ke.co.equitygroup.equitymobile.debug:id/digit4"
VERIFICATION_CODE_5 = "ke.co.equitygroup.equitymobile.debug:id/digit5"
VERIFICATION_CODE_6 = "ke.co.equitygroup.equitymobile.debug:id/digit6"
VERIFICATION_BY_SECURITY_QUESTION = "//androidx.cardview.widget.CardView[@resource-id='ke.co.equitygroup.equitymobile.debug:id/home_item_loan']/android.view.ViewGroup"
FIRST_SECURITY_QUESTION_FIELD = "ke.co.equitygroup.equitymobile.debug:id/firstAnswerET"
SECOND_SECURITY_QUESTION_FIELD = "ke.co.equitygroup.equitymobile.debug:id/secondAnswerET"
CONFIRM_SEC_QUE_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/confirm"
SIGNED_IN_DEVICES = "ke.co.equitygroup.equitymobile.debug:id/newDeviceDescription"
NEW_DEVICE_LABEL = "ke.co.equitygroup.equitymobile.debug:id/newDeviceLabel"
DEVICE_LIST = "ke.co.equitygroup.equitymobile.debug:id/recycler"
DEVICE_RADIO_BUTTONS = "ke.co.equitygroup.equitymobile.debug:id/itemRadioButton"
DEVICE_CHECKED = "//android.widget.CheckBox[@checked='true']"
REMOVE_DEVICE_BUTTON = "ke.co.equitygroup.equitymobile.debug:id/removeDeviceButton"
MAIN_TITLE = "ke.co.equitygroup.equitymobile.debug:id/tvTitle"
EACH_DEVICE = "ke.co.equitygroup.equitymobile.debug:id/itemParent"
LAST_ACTIVE_DEVICES = "//android.widget.CheckBox[@resource-id='ke.co.equitygroup.equitymobile.debug:id/itemRadioButton']"
