
BORROW_ICON='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/iconImage"])[6]'
APPLY_ONE_MONTH_NAV='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/imageView"])[1]'
LOAN_PRODUCTS_TEXT='ke.co.equitygroup.equitymobile.debug:id/loansDesc'
LEARN_MORE='xpath=(//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/learnMoreButton"])[1]'
ONE_MONTH_MORE_TEXT='This loan is available to Equity members who have had their Equity bank account for at least six months.\n\nYou can borrow up to 3,000,000 UGX, which can be paid in 1 month.'
ONE_MONTH_MORE_ELEMENT='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/fullDescription"]'
CHECK_LOAN_LIMIT='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/checkLimitButton"]'
UNQUALIFIED_USER_INFO='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/errorDescription"]'
UNQUALIFIED_USER_TEXT='Dear Member, this loan is currently unavailable to you. Please visit the nearest branch for more info on available loans. JH-401 '
ESCAPE_UNQUALIFIED_USER_ERROR='ke.co.equitygroup.equitymobile.debug:id/primaryButton'
APPLY_NOW_BUTTON='ke.co.equitygroup.equitymobile.debug:id/applyButton'
BORROW_AMOUNT_FIELD='//android.widget.EditText[@resource-id="ke.co.equitygroup.equitymobile.debug:id/amountInputValue"]'
PURPOSE_SELECTION='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemDropDown"])[3]'
ACTUAL_PURPOSE='//androidx.recyclerview.widget.RecyclerView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/purposeType"]/android.view.ViewGroup[1]'
CONTINUE_BUTTON='ke.co.equitygroup.equitymobile.debug:id/sendAction'
APPLY_FOR_LOAN_BUTTON='//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/sendAction"]'
LOAN_TERMS_LINK='ke.co.equitygroup.equitymobile.debug:id/termsLink'
TERMS_PAGE_TITLE='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/toolbarTitle"]'
CLOSE_TERMS_BUTTON='ke.co.equitygroup.equitymobile.debug:id/closeTerms'
TERMS_CHECKBOX='ke.co.equitygroup.equitymobile.debug:id/iAcceptRadioButton'
CONFIRM_LOAN_BUTTON='ke.co.equitygroup.equitymobile.debug:id/confirmLoanButton'
REVIEW_CONFIRMATION='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/toolbarTitle"]'
REVIEW_TEXT='Thank you for applying for this loan. Your application is being reviewed. In 20 minutes, you will receive a notification regarding the status of your application. '
TEXT_ELEMENT='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/in_review_desc"]'
DONE_REVIEW='ke.co.equitygroup.equitymobile.debug:id/backToTransactionButton'
OTP_HEADER = '//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/header"]'
BACK_ARROW_FROM_BORROW= '//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/startIcon"]'
EAZZYLOAN_CARD= '//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/containerCardHomeLoan"]'
LOAN_ACTION= '//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/loanAction"]'
MAKE_PAYMENT_BUTTON='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemText" and @text="Make payment"]'
SELECT_LOAN_TO_PAY= 'xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemDropDown"])[2]'
SELECT_THE_LOAN= '//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/radioButton"]'
SELECT_LOAN_AMOUNT= 'xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemDropDown"])[3]'
SELECT_PARTIAL_AMOUNT= 'xpath=(//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/radioButton"])[2]'
PARTIAL_AMOUNT_FIELD= '//android.widget.EditText'
CONTINUE_ACTION_BUTTON= '//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/continueAction"]'
PAID_AMOUNT_ON_CONFIRMATION_SCREEN= '//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/amountValue"]'
LOAN_CHARGES= '//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/feesValue"]'
PAY_LOAN_BUTTON= '//android.widget.Button[@resource-id="ke.co.equitygroup.equitymobile.debug:id/payButton"]'
FULL_AMOUNT_RADIO_BUTTON= 'xpath=(//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/radioButton"])[1]'
FULL_AMOUNT_LOCATOR='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/loanDescription"]'
KES_CURRENCY_ON_AMOUNT_FIELD='//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/amountInputSuffix" and @text="KES"]'
TZ_CURRENCY_ON_AMOUNT_FIELD='//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/amountInputSuffix" and @text="TZS"]'
UG_CURRENCY_ON_AMOUNT_FIELD='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/spinnerStatusTitle" and @text="UGX"]'
SS_CURRENCY_ON_AMOUNT_FIELD='//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/amountInputSuffix" and @text="SSP"]'
RW_CURRENCY_ON_AMOUNT_FIELD='//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/amountInputSuffix" and @text="RWF"]'
SELECT_ANOTHER_ACCOUNT_ICON='xpath=(//android.widget.ImageView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/itemDropDown"])[1]'
SELECT_ACCOUNT_HEADER='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/payFromAccountLabel"]'
ANOTHER_ACCOUNT_RADIOBUTTON='xpath=(//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/radioButton"])[2]'
INSUFFICIENT_FUNDS_ELEMENT='//android.widget.TextView[@resource-id="ke.co.equitygroup.equitymobile.debug:id/errorText"]'
ACCOUNT_DROPDOWN='//android.view.ViewGroup[@resource-id="ke.co.equitygroup.equitymobile.debug:id/payFromParent"]'
FIRST_SUFFICIENT_BALANCE_RADIO_BUTTON='xpath=(//android.widget.CheckBox[@resource-id="ke.co.equitygroup.equitymobile.debug:id/radioButton"])[1]'